### ISSUE TITLE
e60 wake up command

### ISSUE THREAD

**Issue by Dreed420** [Ldogg123/e60-canbus#1]
Czesc, wszyscy w internecie pracuja na zegarach od e90 - moje pytanie czy komenda wybudzenia jest taka sama jak w e60?

poniewaz u mnie nie dziala zadna z nich, pojawia sie tylko czerwone logo samochodu w powietrzu.

**Comment by Dreed420** [comment]
[0x130]5 	- 45 40 21 8F FE - nie wybudza zegarow e60 :(

**Comment by Ldogg123** [comment]
> [0x130] 5 - 45 40 21 8F FE - does not wake up e60 clocks :(

I believe the e90 and the e60 are similar but they have a lot of differences. I haven't come across the wake-up signal yet, but when / if I do I'll let you know. If you figure it out before me post it here / in the discord!

**Comment by Dreed420** [comment]
discord invite link dont work

**Comment by Ldogg123** [comment]
> discord invite link dont work

Sorry about that, the link should be fixed now. The CANBus channel has a couple more resources than I have here.

**Comment by Ldogg123** [comment]
For anyone coming across this in the future, I posted the wake-up CAN Messages to our wiki [HERE.](https://wiki.bitboucher.com/en/can/kombi)
